// IkaKit — Constants
// Dữ liệu game Ikariam: buildings, units, ships

export const Buildings = Object.freeze({
  TOWN_HALL:             'townHall',
  PALACE:                'palace',
  GOVERNORS_RESIDENCE:   'palaceColony',
  TAVERN:                'tavern',
  MUSEUM:                'museum',
  ACADEMY:               'academy',
  WORKSHOP:              'workshop',
  TEMPLE:                'temple',
  EMBASSY:               'embassy',
  WAREHOUSE:             'warehouse',
  DUMP:                  'dump',
  TRADING_PORT:          'port',
  TRADING_POST:          'branchOffice',
  BLACK_MARKET:          'blackMarket',
  MARINE_CHART_ARCHIVE:  'marineChartArchive',
  DOCKYARD:              'dockyard',
  WALL:                  'wall',
  HIDEOUT:               'safehouse',
  BARRACKS:              'barracks',
  SHIPYARD:              'shipyard',
  PIRATE_FORTRESS:       'pirateFortress',
  FORESTER:              'forester',
  CARPENTER:             'carpentering',
  WINERY:                'winegrower',
  WINE_PRESS:            'vineyard',
  STONEMASON:            'stonemason',
  ARCHITECT:             'architect',
  GLASSBLOWER:           'glassblowing',
  OPTICIAN:              'optician',
  ALCHEMISTS_TOWER:      'alchemist',
  FIREWORK_TEST_AREA:    'fireworker',
});

export const BuildingsId = Object.freeze({
  townHall:           0,
  palace:             11,
  palaceColony:       17,
  tavern:             9,
  museum:             10,
  academy:            4,
  workshop:           15,
  temple:             28,
  embassy:            12,
  warehouse:          7,
  dump:               29,
  port:               3,
  branchOffice:       13,
  blackMarket:        31,
  marineChartArchive: 32,
  dockyard:           33,
  wall:               8,
  safehouse:          16,
  barracks:           6,
  shipyard:           5,
  pirateFortress:     30,
  forester:           18,
  carpentering:       23,
  winegrower:         21,
  vineyard:           26,
  stonemason:         19,
  architect:          24,
  glassblowing:       20,
  optician:           25,
  alchemist:          22,
  fireworker:         27,
});

export const Military = Object.freeze({
  // Lục quân
  HOPLITE:           'phalanx',
  STEAM_GIANT:       'steamgiant',
  SPEARMAN:          'spearman',
  SWORDSMAN:         'swordsman',
  SLINGER:           'slinger',
  ARCHER:            'archer',
  GUNNER:            'marksman',
  BATTERING_RAM:     'ram',
  CATAPULT:          'catapult',
  MORTAR:            'mortar',
  GYROCOPTER:        'gyrocopter',
  BALLOON_BOMBADIER: 'bombardier',
  COOK:              'cook',
  DOCTOR:            'medic',
  SPARTAN:           'spartan',

  // Hải quân
  FLAME_THROWER:     'ship_flamethrower',
  STEAM_RAM:         'ship_steamboat',
  RAM_SHIP:          'ship_ram',
  CATAPULT_SHIP:     'ship_catapult',
  BALLISTA_SHIP:     'ship_ballista',
  MORTAR_SHIP:       'ship_mortar',
  ROCKET_SHIP:       'ship_rocketship',
  SUBMARINE:         'ship_submarine',
  PADDLE_SPEED_SHIP: 'ship_paddlespeedship',
  BALLOON_CARRIER:   'ship_ballooncarrier',
  TENDER:            'ship_tender',
});

export const UnitIds = Object.freeze({
  301: 'slinger',
  302: 'swordsman',
  303: 'phalanx',
  304: 'marksman',
  305: 'mortar',
  306: 'catapult',
  307: 'ram',
  308: 'steamgiant',
  309: 'bombardier',
  310: 'cook',
  311: 'medic',
  312: 'gyrocopter',
  313: 'archer',
  315: 'spearman',
  316: 'barbarian',
  319: 'spartan',

  210: 'ship_ram',
  211: 'ship_flamethrower',
  212: 'ship_submarine',
  213: 'ship_ballista',
  214: 'ship_catapult',
  215: 'ship_mortar',
  216: 'ship_steamboat',
  217: 'ship_rocketship',
  218: 'ship_paddlespeedship',
  219: 'ship_ballooncarrier',
  220: 'ship_tender',
});
